GET http://localhost:3000/subscribers

###

GET http://localhost:3000/subscribers/5e5647f91fbcbf0334963578

###

POST http://localhost:3000/subscribers
Content-Type: application/json

{
    "name": "Aglio Dude",
    "subscribedToChannel": "Vsauce2"
}